### ISSUE TITLE
Tracking issues of storage connectors migration

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#1483]
This issue is used to track the overall progress of storage connectors migration. We expect to migrate all of them before releasing `0.4.0`.

This issue will close https://github.com/mozilla/sccache/issues/1404

## Tasks

- [x] s3
- [x] azure (azblob)
- [x] gcs (wait for https://github.com/mozilla/sccache/pull/1494)
- [x] ~~fs~~ *(we need to port the lru cache first, should in another issue.*)
- [x] https://github.com/mozilla/sccache/pull/1509
- [x] gha (wait for https://github.com/mozilla/sccache/pull/1528)
- [x] Memcached (wait for https://github.com/mozilla/sccache/pull/1545)

**Comment by Xuanwo** [comment]
All works have been done, let's close!
