### ISSUE TITLE
Rust caching followup improvements

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#84]
I'm punting on a few things for the first cut at Rust support:
- [ ] [Handle rustup overrides](https://github.com/mozilla/sccache/issues/87)
- [x] [Support linking against native libraries](https://github.com/mozilla/sccache/issues/88)
- [x] [Cache CARGO_ environment variables](https://github.com/mozilla/sccache/issues/89)

**Comment by drahnr** [comment]
Ref #666

**Comment by drahnr** [comment]
Can be closed.
